name: ais_wrangling
channels:
  - conda-forge
dependencies:
  - python==3.6
  - python-dateutil==2.8.1
  - pandas==1.3.0
  - numpy==1.20.1
  - numpy-ext==0.9.4
  - numpydoc==0.7.0
  - matplotlib==3.4.2
